# le nom de l'hôte ou groupe concerné
---
- hosts: master_node
  roles:
    - elastic.elasticsearch
  vars:
    es_instance_name: "elmaster"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "{{groups['master_node'][0]}}:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: "{{node_data_master_node}}"
      node.master: "{{node_master_master_node}}"
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{groups['master_node'][0]}}"
    es_enable_xpack: false

- hosts: master_node
  roles:
    - ansible-install-curator
  vars:
    service_name: curator

- hosts: data_node
  roles:
    - elastic.elasticsearch
  vars:
    es_instance_name: "eldata"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "{{groups['master_node'][0]}}:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: "{{node_data_data_node}}"
      node.master: "{{node_master_data_node}}"
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{inventory_hostname}}"
    es_enable_xpack: false

- hosts: client_node
  roles:
    - elastic.elasticsearch
  vars:
    es_instance_name: "elclient"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "{{groups['master_node'][0]}}:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: "{{node_data_client_node}}"
      node.master: "{{node_master_client_node}}"
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{inventory_hostname}}"
    es_enable_xpack: false