---
- hosts: master_node
  roles:
    - ansible-elasticsearch
  vars:
    es_version: 7.1.0
    es_instance_name: "elmaster"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes:
        - "{{groups['master_node'][0]}}"
      discovery.seed_hosts: "{{groups['master_node'][0]}}:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      node.ingest: false
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_api_host: "{{inventory_hostname}}"
    es_enable_xpack: false
    es_templates: false
    es_version_lock: false

- hosts: master_node
  roles:
    - ansible-install-curator
  vars:
    service_name: curator

- hosts: data_node
  roles:
    - ansible-elasticsearch
  vars:
    es_version: 7.1.0
    es_instance_name: "eldata"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes:
        - "{{groups['master_node'][0]}}"
      discovery.seed_hosts: "{{groups['master_node'][0]}}:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      node.ingest: false
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_api_host: "{{inventory_hostname}}"
    es_enable_xpack: false
    es_templates: false
    es_version_lock: false

- hosts: client_node
  roles:
    - ansible-elasticsearch
  vars:
    es_version: 7.1.0
    es_instance_name: "elclient"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes:
        - "{{groups['master_node'][0]}}"
      discovery.seed_hosts: "{{groups['master_node'][0]}}:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: false
      node.ingest: true
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_api_host: "{{inventory_hostname}}"
    es_enable_xpack: false
    es_templates: false
    es_version_lock: false