# le nom de l'hôte ou groupe concerné
---
- hosts: master_node_1
  roles:
    - elastic.elasticsearch
  vars:
    es_instance_name: "{{es_instance_name_master_node_1}}"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "{{discovery_zen_ping_unicast_hosts}}"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: "{{node_data_master_node_1}}"
      node.master: "{{node_master_master_node_1}}"
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{es_api_host_master_node_1}}"
    es_enable_xpack: false

- hosts: data_node_1
  roles:
    - elastic.elasticsearch
  vars:
    es_instance_name: "{{es_instance_name_data_node_1}}"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "{{discovery_zen_ping_unicast_hosts}}"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: "{{node_data_data_node_1}}"
      node.master: "{{node_master_data_node_1}}"
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{es_api_host_data_node_1}}"
    es_enable_xpack: false

- hosts: data_node_2
  roles:
    - elastic.elasticsearch
  vars:
    es_instance_name: "{{es_instance_name_data_node_2}}"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "{{discovery_zen_ping_unicast_hosts}}"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: "{{node_data_data_node_2}}"
      node.master: "{{node_master_data_node_2}}"
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{es_api_host_data_node_2}}"
    es_enable_xpack: false

- hosts: client_node_1
  roles:
    - elastic.elasticsearch
  vars:
    es_instance_name: "{{es_instance_name_client_node_1}}"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "{{discovery_zen_ping_unicast_hosts}}"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: "{{node_data_client_node_1}}"
      node.master: "{{node_master_client_node_1}}"
      bootstrap.memory_lock: false
      network.host: _enp0s3_
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_host: "{{es_api_host_client_node_1}}"
    es_enable_xpack: false