# le nom de l'hôte ou groupe concerné
---
- hosts: kibana
  roles:
    - ansible-install-kibana
  vars:
    service_name: kibana
    kibana_hostname: "{{inventory_hostname}}"
    kibana_elasticsearch_url: "http://{{groups['master_node'][0]}}:9200"
