# le nom de l'hôte ou groupe concerné
---
- hosts: kibana
  roles:
    - ansible-install-kibana
  vars:
    service_name: kibana
    kibana_hostname: "{{groups['kibana'][0]}}"
    kibana_elasticsearch_url: "http://{{groups['master_node'][0]}}:9200"
