version: "2.1"
services:
    gitlab-ce:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab-ce
        hostname: gitlab-ce
        ports:
            - "443:443"
            - "80:80"
            - "22:22"
        volumes:
            - ./gitlab/var-opt-gitlab:/var/opt/gitlab
            - ./gitlab/var-log-gitlab:/var/log/gitlab
            - ./gitlab/etc-gitlab:/etc/gitlab
        environment:
            - 'GITLAB_OMNIBUS_CONFIG=gitlab_rails[''monitoring_whitelist''] = [''127.0.0.0/8''];gitlab_rails[''initial_shared_runners_registration_token''] = ''${REGISTRATION_TOKEN}'';gitlab_rails[''initial_root_password''] = ''${ROOT_PASSWORD}'''
        healthcheck:
            test: "wget http://localhost/-/health"
            interval: 2s
            timeout: 5s
            retries: 100
    gitlab-runner:
        image: gitlab/gitlab-runner:latest
        container_name: gitlab-runner
        hostname: gitlab-runner
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            gitlab-ce:
                condition: service_healthy
        restart: on-failure